export const NOTIFICATION_TYPE_SUCCESS = 'NOTIFICATION_TYPE_SUCCESS';
export const NOTIFICATION_TYPE_WARNING = 'NOTIFICATION_TYPE_WARNING';
export const NOTIFICATION_TYPE_ERROR = 'NOTIFICATION_TYPE_ERROR';

export const BORDER_SIZE = 6;
export const MAX_RESIZE_EXPANDABLE_SIZE = 600;
export const MIN_RESIZE_EXPANDABLE_SIZE = 250;
